project_name: plist
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
nfpms:
  - maintainer: Aurelio Calegari (aureliocalegari@gmail.com)
    description: Apple's PLIST converter
    homepage: https://github.com/aurc/plist
    license: Apache 2.0
    formats:
      - deb
      - rpm
      - apk