name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
  godeploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Tag and Deploy
        run: |
        git fetch --prune --unshallow
        git describe --tags
        CURV=$(git describe --tags --abbrev=0)
        IFS='.' read -ra VR <<< "$CURV"
        INC=`expr ${VR[2]} + 1`
        FV="${VR[0]}.${VR[1]}.$INC"
        echo $FV
        shell: bash
